datasets:
  - id: "data_sharing_dataset"
    friendly_name: "Data Sharing Dataset"
    description: "Dataset for sharing data between different parties"
    labels:
      environment: "development"
      purpose: "data_sharing"
    access_rules:
      - role: "OWNER"
        special_group: "projectOwners"
      - role: "READER"
        special_group: "projectReaders"
      - role: "WRITER"
        special_group: "projectWriters"

  # Example of how to add more datasets
  - id: "analytics_dataset"
    friendly_name: "Analytics Dataset"
    description: "Dataset for analytics data"
    labels:
      environment: "development"
      purpose: "analytics"
    access_rules:
      - role: "OWNER"
        special_group: "projectOwners"
      - role: "READER"
        special_group: "projectReaders" 


  - id: "tpe_mrt_bronze"
    friendly_name: "Taipei MRT Bronze"
    description: "Raw data from Taipei MRT including traffic, station, and exit information"
    labels:
      environment: "development"
      domain: "tpe_mrt"
      data_tier: "bronze"
      owner: "data_engineering"
    access_rules:
      # Project owners always have access
      - role: "OWNER"
        special_group: "projectOwners"
      
      # Project writers have write access
      - role: "WRITER"
        special_group: "projectWriters"
      
      # Project readers have read access
      - role: "READER"
        special_group: "projectReaders"


  - id: "tpe_mrt_silver"
    friendly_name: "Taipei MRT Silver"
    description: "Cleaned and validated Taipei MRT data"
    labels:
      environment: "development"
      domain: "tpe_mrt"
      data_tier: "silver"
      owner: "data_engineering"
    access_rules:
      - role: "OWNER"
        special_group: "projectOwners"
      - role: "WRITER"
        special_group: "projectWriters"
      - role: "READER"
        special_group: "projectReaders"


  - id: "tpe_mrt_gold"
    friendly_name: "Taipei MRT Gold"
    description: "Analytics-ready Taipei MRT data for business consumption"
    labels:
      environment: "development"
      domain: "tpe_mrt"
      data_tier: "gold"
      owner: "data_engineering"
    access_rules:
      - role: "OWNER"
        special_group: "projectOwners"
      - role: "WRITER"
        special_group: "projectWriters"
      - role: "READER"
        special_group: "projectReaders"

