datasets:
  # - id: "data_sharing_dataset"
  #   friendly_name: "Data Sharing Dataset"
  #   description: "Dataset for sharing data between different parties"
  #   labels:
  #     environment: "development"
  #     purpose: "data_sharing"
  #   access_rules:
  #     - role: "OWNER"
  #       special_group: "projectOwners"
  #     - role: "READER"
  #       special_group: "projectReaders"
  #     - role: "WRITER"
  #       special_group: "projectWriters"


  - id: "tpe_mrt_bronze"
    friendly_name: "Taipei MRT Bronze"
    description: "Raw data from Taipei MRT including traffic, station, and exit information"
    labels:
      environment: "development"
      domain: "tpe_mrt"
      data_tier: "bronze"
      owner: "data_engineering"
    access_rules:
      # Project owners always have access
      - role: "OWNER"
        special_group: "projectOwners"
      
      # Project writers have write access
      - role: "WRITER"
        special_group: "projectWriters"
      
      # Project readers have read access
      - role: "READER"
        special_group: "projectReaders"

  - id: "tpe_mrt_silver"
    friendly_name: "Taipei MRT Silver"
    description: "Cleaned and validated Taipei MRT data"
    labels:
      environment: "development"
      domain: "tpe_mrt"
      data_tier: "silver"
      owner: "data_engineering"
    access_rules:
      - role: "OWNER"
        special_group: "projectOwners"
      - role: "WRITER"
        special_group: "projectWriters"
      - role: "READER"
        special_group: "projectReaders"

  - id: "tpe_mrt_gold"
    friendly_name: "Taipei MRT Gold"
    description: "Analytics-ready Taipei MRT data for business consumption"
    labels:
      environment: "development"
      domain: "tpe_mrt"
      data_tier: "gold"
      owner: "data_engineering"
    access_rules:
      - role: "OWNER"
        special_group: "projectOwners"
      - role: "WRITER"
        special_group: "projectWriters"
      - role: "READER"
        special_group: "projectReaders"

  - id: "general"
    friendly_name: "General purpose dataset"
    description: "For storing general purpose data such as Calendar, Holidays, etc."
    labels:
      environment: "development"
      domain: "general"
      data_tier: "general"
      owner: "data_engineering"
    access_rules:
      - role: "OWNER"
        special_group: "projectOwners"
      - role: "WRITER"
        special_group: "projectWriters"
      - role: "READER"
        special_group: "projectReaders"

  - id: "workspace"
    friendly_name: "workspace"
    description: "For testing and development purposes, or temporary data storage"
    labels:
      environment: "development"
      domain: "workspace"
      data_tier: "none"
      owner: "data_engineering"
    access_rules:
      - role: "OWNER"
        special_group: "projectOwners"
      - role: "WRITER"
        special_group: "projectWriters"
      - role: "READER"
        special_group: "projectReaders"

  - id: "reference"
    friendly_name: "Reference Data"
    description: "Conformed, master data (dimensions) for enrichment, e.g., boundaries, calendars."
    labels:
      environment: "development"
      domain: "reference"
      data_tier: "silver"
      owner: "data_engineering"
    access_rules:
      - role: "OWNER"
        special_group: "projectOwners"
      - role: "WRITER"
        special_group: "projectWriters"
      - role: "READER"
        special_group: "projectReaders"

  - id: "osm_silver"
    friendly_name: "OSM Silver"
    description: "Cleaned and validated data from OpenStreetMap"
    labels:
      environment: "development"
      domain: "osm"
      data_tier: "silver"
      owner: "data_engineering"
    access_rules:
      - role: "OWNER"
        special_group: "projectOwners"
      - role: "WRITER"
        special_group: "projectWriters"
      - role: "READER"
        special_group: "projectReaders"

  - id: "osm_gold"
    friendly_name: "OSM Gold"
    description: "Analytics-ready OpenStreetMap data for business consumption"
    labels:
      environment: "development"
      domain: "osm"
      data_tier: "gold"
      owner: "data_engineering"
    access_rules:
      - role: "OWNER"
        special_group: "projectOwners"
      - role: "WRITER"
        special_group: "projectWriters"
      - role: "READER"
        special_group: "projectReaders"

  - id: "c_store_bronze"
    friendly_name: "Convinence Store bronze"
    description: "Convinence Store site locations"
    labels:
      environment: "development"
      domain: "c_store"
      data_tier: "bronze"
      owner: "data_engineering"
    access_rules:
      - role: "OWNER"
        special_group: "projectOwners"
      - role: "WRITER"
        special_group: "projectWriters"
      - role: "READER"
        special_group: "projectReaders"

  - id: "c_store_silver"
    friendly_name: "Convinence Store silver"
    description: "Convinence Store site locations"
    labels:
      environment: "development"
      domain: "c_store"
      data_tier: "silver"
      owner: "data_engineering"
    access_rules:
      - role: "OWNER"
        special_group: "projectOwners"
      - role: "WRITER"
        special_group: "projectWriters"
      - role: "READER"
        special_group: "projectReaders"

  - id: "railway_silver"
    friendly_name: "Railway silver"
    description: "Railway station site locations and lines"
    labels:
      environment: "development"
      domain: "railway"
      data_tier: "silver"
      owner: "data_engineering"
    access_rules:
      - role: "OWNER"
        special_group: "projectOwners"
      - role: "WRITER"
        special_group: "projectWriters"
      - role: "READER"
        special_group: "projectReaders"

  - id: "bus_silver"
    friendly_name: "Bus silver"
    description: "Bus station site locations and lines"
    labels:
      environment: "development"
      domain: "bus"
      data_tier: "silver"
      owner: "data_engineering"
    access_rules:
      - role: "OWNER"
        special_group: "projectOwners"
      - role: "WRITER"
        special_group: "projectWriters"
      - role: "READER"
        special_group: "projectReaders"
