datasets:
  - dataset_id_var_name: "sales_dataset_id"
    friendly_name: "Sales Data"
    description: "Dataset for sales related information"
    labels:
      team: "analytics"
      goog-terraform-provisioned: "true"

  - dataset_id_var_name: "marketing_dataset_id"
    friendly_name: "Marketing Data"
    description: "Dataset for marketing campaigns and leads"
    labels:
      team: "marketing"
      goog-terraform-provisioned: "true"

  # Add more datasets here as needed
  # Example:
  # - dataset_id_var_name: "finance_dataset_id"
  #   friendly_name: "Finance Data"
  #   description: "Dataset for financial records"
  #   labels:
  #     team: "finance"
  #     goog-terraform-provisioned: "true" 